pypro/aperitivos/urls.py
from django.urls import path
from pypro.aperitivos.views import video, indice

app_name = 'aperitivos'
urlpatterns = [
    path('', indice, name='indice'),
    path('<slug:slug>', video, name='video'),
]

pypro/base/urls.py
from django.urls import path
from pypro.base.views import home

app_name = 'base'
urlpatterns = [
    path('', home, name='home'),
]

pypro/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls, name='admin'),
    path('', include('pypro.base.urls')),
    path('aperitivos/', include('pypro.aperitivos.urls')),
]

if settings.DEBUG:
    urlpatterns.append(path('__debug__/', include('debug_toolbar.urls')))

pypro/aperitivos/models.py
from django.db import models
from django.urls import reverse


class Video(models.Model):
    titulo = models.CharField(max_length=32)
    slug = models.SlugField(max_length=32)
    vimeo_id = models.CharField(max_length=32)
    creation = models.DateTimeField(auto_now_add=True)

    def get_absolute_url(self):
        return reverse('aperitivos:video', args=(self.slug,))

    def __str__(self):
        return f'Vídeo: {self.titulo}'

pypro/base/models.py
from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
from django.contrib.auth.models import PermissionsMixin
from django.utils.translation import gettext_lazy as _
from django.core.mail import send_mail
from django.utils import timezone
from django.db import models


class UserManager(BaseUserManager):
    use_in_migration = True

    def _create_user(self, email, password=None, **extra_fields):
        """
        Creates and saves a User with the given email and password.
        """
        if not email:
            raise ValueError('Users must have an email address')

        user = self.model(
            email=self.normalize_email(email),
            **extra_fields
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_user(self, email, password=None, **extra_fields):
        extra_fields.setdefault('is_superuser', False)
        return self._create_user(email, password, **extra_fields)

    def create_superuser(self, email, password=None, **extra_fields):
        """
        Creates and saves a superuser with the given email and password.
        """
        extra_fields.setdefault('is_superuser', True)
        extra_fields.setdefault('is_staff', True)

        if extra_fields.get('is_superuser') is not True:
            raise ValueError('Superuser must have is_superuser=True.')
        if extra_fields.get('is_staff') is not True:
            raise ValueError('Superuser must have is_staff=True.')

        return self._create_user(email, password, **extra_fields)


class User(AbstractBaseUser, PermissionsMixin):
    """
    App base User class.

    Email and password are required. Other fields are optional.
    """

    first_name = models.CharField(_("first name"), max_length=150, blank=True)
    email = models.EmailField(_("email address"), unique=True)
    is_staff = models.BooleanField(
        _("staff status"),
        default=False,
        help_text=_("Designates whether the user can log into this admin site."),
    )
    is_active = models.BooleanField(
        _("active"),
        default=True,
        help_text=_(
            "Designates whether this user should be treated as active. "
            "Unselect this instead of deleting accounts."
        ),
    )
    date_joined = models.DateTimeField(_("date joined"), default=timezone.now)

    objects = UserManager()

    EMAIL_FIELD = "email"
    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = _("user")
        verbose_name_plural = _("users")

    def clean(self):
        super().clean()
        self.email = self.__class__.objects.normalize_email(self.email)

    def get_full_name(self):
        """
        Return the first_name.
        """
        full_name = "%s" % self.first_name
        return full_name.strip()

    def get_short_name(self):
        """Return the short name for the user."""
        return self.first_name

    def email_user(self, subject, message, from_email=None, **kwargs):
        """Send an email to this user."""
        send_mail(subject, message, from_email, [self.email], **kwargs)

pypro/modulos/models.py
from django.db import models
from ordered_model.models import OrderedModel
from django.urls import reverse


class Modulo(OrderedModel):
    titulo = models.CharField(max_length=62)
    publico = models.TextField()
    descricao = models.TextField()
    slug = models.SlugField(unique=True)


    def __str__(self):
        return self.titulo

    def get_absolute_url(self):
        return reverse('modulos:detalhe', kwargs={'slug': self.slug})

pypro/aperitivos/views.py
from django.shortcuts import render, get_object_or_404

from pypro.aperitivos.models import Video


def indice(request):
    videos = Video.objects.order_by('creation').all()
    return render(request, 'aperitivos/indice.html', context={'videos': videos})


def video(request, slug):
    video = get_object_or_404(Video, slug=slug)
    return render(request, 'aperitivos/video.html', context={'video': video})

pypro/base/views.py
from django.shortcuts import render


def home(request):
    return render(request, 'base/home.html', {})

pypro/modulos/views.py
from django.shortcuts import render

# Create your views here.

pypro/aperitivos/templates/aperitivos/indice.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Lista de vídeos gratuitos {% endblock %}
{% block description %}Página com a lista de todos os vídeos gratuitos do curso.{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">Lista de vídeos gratuitos</h1>
            <ol>
                {% for video in videos %}
                <li><a href="{{ video.get_absolute_url }}" target="_blank">{{ video.titulo }}</a></li>
                {% empty %}
                Nenhum vídeo disponível.
                {% endfor %}
            </ol>
        </div>
    </div>
</div>
{% endblock body %}

pypro/aperitivos/templates/aperitivos/video.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}{{ video.titulo }}{% endblock title %}
{% block description %}Página com vídeo gratuito de Python.{% endblock description %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <h1 class="mt-4 mb-3">{{ video.titulo | default:"Título em branco" }}</h1>
            <iframe src="https://player.vimeo.com/video/{{ video.vimeo_id }}" width="640" height="360" frameborder="0"
                    allow="autoplay; fullscreen; picture-in-picture" allowfullscreen></iframe>
        </div>
    </div>
</div>
{% endblock body %}

pypro/base/templates/base/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>{% block title %}Python Pro{% endblock title %}</title>

    <meta name="description" content="{% block description %}Página do curso Python Pro{% endblock description %}">
    <meta name="author" content="Leonardo Oliveira">
    <link rel='icon' type='image/png' href="{% static 'img/favicon.png' %}"/>
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
</head>
<body>
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'base:home' %}">PythonPro</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Módulos
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for modulo in MODULOS %}
                        <a class="dropdown-item" href="#">{{ modulo.titulo }}</a>
                        <div class="dropdown-divider"></div>
                        {% endfor %}
                    </div>
                </li>
            </ul>
        </div>
    </div>
</nav>

{% block body %}{% endblock body %}
{% include 'base/footer.html' with contato_email='ramalho@pythonpro.com.br' only %}
</body>
</html>

pypro/base/templates/base/footer.html
<footer class="main-footer mt-5 pt-4 text-light">
    <div class="container">
        <div class="row">
            <div class="col">
                <h3>Entre em contato:</h3>
                <address>
                    +55 11 99999-9999
                    <br>
                    <a href="mailto:{{ contato_email }}" class="text-light">{{ contato_email }}</a>
                </address>
            </div>
        </div>
    </div>
    <div class="rights pt-2">
        <div class="container">
            <div class="row">
                <div class="col">
                    {% now 'Y' %} Python Pro. Todos direitos reservados.
                </div>
            </div>
        </div>
    </div>
</footer>

pypro/base/templates/base/home.html
{% extends 'base/base.html' %}
{% load static %}
{% block title %}Python Pro - Home{% endblock title %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-12">
            <div class="jumbotron">
                <h2>Curso de Python com Luciano Ramalho</h2>
                <h4 class="mt-4">Matrículas abertas, custo R$999,90</h4>
                <!-- INICIO DO BOTAO PAGSEGURO -->
                <a href="https://pag.ae/7YeBrNuG4/button" target="_blank"
                   title="Pagar com PagSeguro"><img
                        src="//assets.pagseguro.com.br/ps-integration-assets/botoes/pagamentos/205x30-pagar.gif"
                        alt="Pague com PagSeguro - é rápido, grátis e seguro!"/></a>
                <!-- FIM DO BOTAO PAGSEGURO -->

                <!--                <h4 class="mt-4">Entre na fila de espera</h4>-->


                <!--                <form action="https://blogspot.us7.list-manage.com/subscribe/post?u=d1f608d8da33795ad29eb0f77&amp;id=fcd29dbd35"-->
                <!--                      method="post" id="mc-embedded-subscribe-form" name="mc-embedded-subscribe-form"-->
                <!--                      class="form-row align-items-center" target="_blank" novalidate>-->

                <!--                    <div class="form-row align-items-center">-->
                <!--                        <div class="col-auto">-->
                <!--                            <label class="sr-only" for="mce-FNAME">Nome</label>-->
                <!--                            <input type="text" value="" name="FNAME" class="form-control mb-2" id="mce-FNAME"-->
                <!--                                   placeholder="Nome">-->
                <!--                        </div>-->

                <!--                        <div class="col-auto">-->
                <!--                            <label class="sr-only" for="mce-EMAIL">Email</label>-->
                <!--                            <input type="email" value="" name="EMAIL" class="form-control mb-2 required" id="mce-EMAIL"-->
                <!--                                   placeholder="exemplo@email.com">-->
                <!--                        </div>-->

                <!--                        &lt;!&ndash; real people should not fill this in and expect good things - do not remove this or risk form bot signups&ndash;&gt;-->
                <!--                        <div style="position: absolute; left: -5000px;" aria-hidden="true">-->
                <!--                            <input type="text"-->
                <!--                                   name="b_d1f608d8da33795ad29eb0f77_fcd29dbd35"-->
                <!--                                   tabindex="-1"-->
                <!--                                   value="">-->
                <!--                        </div>-->

                <!--                        <div class="col-auto">-->
                <!--                            <input type="submit" value="Salvar" name="subscribe" id="mc-embedded-subscribe"-->
                <!--                                   class="btn btn-primary mb-2">-->
                <!--                        </div>-->
                <!--                    </div>-->
                <!--                </form>-->

            </div>
            <div class="row">
                <div class="col-md-12">
                    <div class="card bg-default">
                        <lt>
                            <lt class="lt-highlighter__wrapper">
                                <lt class="lt-highlighter__scroll-element">
                                </lt>
                            </lt>
                        </lt>
                        <h5 class="card-header">
                            Conheça um pouco mais o instrutor
                        </h5>
                        <div class="card-body">
                            <p class="card-text">
                                <img src="{% static 'img/luciano-ramalho.jpg' %}" class="img-thumbnail float-left mr-3"
                                     alt="Foto Luciano Ramalho">
                                Ramalho é sócio e professor na
                                <a href="http://turing.com.br" target="_blank">Oficina Turing</a> e
                                <a href="http://python.pro.br" target="_blank">Python.pro.br</a>.
                                Foi diretor técnico do
                                <a href="http://pt.wikipedia.org/wiki/Brasil_Online" target="_blank">Brasil Online</a>,
                                primeiro portal da Abril S/A na Web.
                                Liderou times para os portais IDG Now, BOL, UOL, AOL Brasil e outros, usando Python
                                desde 1998.
                                Como instrutor, atendeu clientes como Globo.com, Sesc, Itaú, Serpro e Presidência da
                                República. Ajudou a criar a Associação Python Brasil e foi seu presidente. É membro da
                                Python Software Foundation e um dos fundadores do
                                <a href="https://garoa.net.br" target="_blank">Garoa Hacker Clube</a>,
                                o primeiro
                                hackerspace do Brasil. Já palestrou várias vezes em eventos internacionais como FISL,
                                <a href="http://www.oscon.com/oscon2013/public/schedule/detail/29389" target="_blank">
                                    O’Reilly Open Source Convention</a>
                                e <a href="https://us.pycon.org/2013/speaker/profile/165/" target="_blank">PyCon US</a>.
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock body %}